spring.application.name=Movie Browsing Catalogue
# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/hbv
spring.datasource.username=hbv
spring.datasource.password=hbv
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
